name: TskNet.Native - Build & Pack

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["main", "develop" ]

env:
  BUILD_NUMBER: ${{ github.run_number }}
jobs:
  build-aff:
    uses: ./.github/workflows/build-aff-lib.yml
    with:
      artifact-name: libaff
  build-vhdi:
    uses: ./.github/workflows/build-libyal-dependency.yml
    with:
      artifact-name: libvhdi
      repo-name: libyal/libvhdi
      repo-ref: 20251119
      dependencies: autoconf automake autopoint build-essential libfuse3-dev
  build-vmdk:
    uses: ./.github/workflows/build-libyal-dependency.yml
    with:
      artifact-name: libvmdk
      repo-name: libyal/libvmdk
      repo-ref: 20240510
      dependencies: autoconf automake autopoint build-essential libfuse3-dev
  build-slvm:
    uses: ./.github/workflows/build-libyal-dependency.yml
    with:
      artifact-name: libslvm
      repo-name: libyal/libvslvm
      repo-ref: 20240504
      dependencies: autoconf automake autopoint libtool pkg-config
  build-bfio:
    uses: ./.github/workflows/build-libyal-dependency.yml
    with:
      artifact-name: libbfio
      repo-name: libyal/libbfio
      repo-ref: 20240414
      dependencies: autoconf automake autopoint libtool pkg-config
  build-sleuthkit:
    needs: [build-aff, build-vhdi, build-vmdk, build-slvm, build-bfio]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: sleuthkit/sleuthkit
          ref: sleuthkit-4.14.0
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          merge-multiple: true
          path: artifacts
      - name: install_dependencies
        run: sudo apt-get -y install libcurl4-openssl-dev
      - name: Generate sleuthkit
        run: |
          ./bootstrap
          ./configure --prefix=${{ github.workspace }}/artifacts \ 
                      --disable-static --enabled-shared \
                      --with-afflib=${{ github.workspace }}/artifacts \
                      --with-libbfio=${{ github.workspace }}/artifacts \
                      --with-libvhdi=${{ github.workspace }}/artifacts \
                      --with-libvmdk=${{ github.workspace }}/artifacts \
                      --with-libvslvm=${{ github.workspace }}/artifacts
          make
          make install
      - name: Upload nupkg
        uses: actions/upload-artifact@v6
        with:
          name: sleuthkit-lib
          path: ${{ github.workspace }}/artifacts